Repository RoadTripMoustache/kana_to_kanji, pull requests merged in 2023-09, with the labels that each got.

#45 Settings view
  .github/workflows/pr_workflow.yaml
  lib/main.dart
  lib/src/app.dart
  lib/src/core/constants/preference_flags.dart
  lib/src/core/repositories/settings_repository.dart
  lib/src/core/services/info_service.dart
  lib/src/core/services/preferences_service.dart
  lib/src/core/widgets/app_scaffold.dart
  lib/src/locator.dart
  lib/src/quiz/prepare/prepare_quiz_view.dart
  lib/src/quiz/prepare/prepare_quiz_view_model.dart
  lib/src/router.dart
  lib/src/settings/settings_view.dart
  lib/src/settings/settings_view_model.dart
  lib/src/settings/widgets/heading_item.dart
  lib/src/settings/widgets/tile_item.dart
  localization/en.arb
  pubspec.lock
  pubspec.yaml
  test/src/core/repositories/settings_repository_test.dart
  test/src/core/services/preferences_service_test.dart
  test/src/settings/settings_view_model_test.dart
  test/src/settings/widgets/heading_item_test.dart
  test/src/settings/widgets/tile_item_test.dart
Labels: enhancement, version: Minor, feature: settings

#48 Implement Isar
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  docs/tooling/isar.md
  lib/src/core/models/group.dart
  lib/src/core/models/kana.dart
  lib/src/core/repositories/groups_repository.dart
  lib/src/core/repositories/kana_repository.dart
  lib/src/core/services/api_service.dart
  lib/src/core/services/database_service.dart
  lib/src/core/services/groups_service.dart
  lib/src/core/services/kana_service.dart
  lib/src/locator.dart
  lib/src/quiz/quiz_view_model.dart
  pubspec.lock
  pubspec.yaml
  test/src/core/repositories/groups_repository_test.dart
  test/src/quiz/conclusion/quiz_conclusion_view_model_test.dart
  test/src/quiz/conclusion/widgets/question_review_tile_test.dart
  test/src/quiz/conclusion/widgets/to_review_section_test.dart
  test/src/quiz/prepare/widgets/group_card_test.dart
Labels: version: Minor

#51 Add i10n FR support
  README.md
  ios/Runner/Info.plist
  localization/fr.arb
  pubspec.yaml
Labels: version: Minor

#57 chore: Setup Firebase and Crashlytics
  .github/workflows/main-workflow.yaml
  .github/workflows/pr_workflow.yaml
  .gitignore
  README.md
  analysis_options.yaml
  android/app/build.gradle
  android/build.gradle
  ios/Runner.xcodeproj/project.pbxproj
  lib/src/app.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, version: Patch, CI/CD, platform: iOS, platform: android

#58 ci: Split the android build per abi to reduce apk size
  .github/workflows/main-workflow.yaml
  .github/workflows/pr_workflow.yaml
Labels: CI/CD

#59 feat: Add language configuration in settings
  README.md
  lib/src/app.dart
  lib/src/core/constants/preference_flags.dart
  lib/src/core/repositories/settings_repository.dart
  lib/src/settings/settings_view.dart
  lib/src/settings/settings_view_model.dart
  localization/en.arb
  localization/fr.arb
  pubspec.yaml
  test/src/core/repositories/settings_repository_test.dart
Labels: enhancement, version: Minor

#62 feat: App configuration using .env
  .env.template
  .github/workflows/main-workflow.yaml
  .github/workflows/pr_workflow.yaml
  .gitignore
  README.md
  lib/src/core/constants/app_configuration.dart
  lib/src/core/services/api_service.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, version: Patch, CI/CD, platform: iOS, platform: web, platform: android

#64 feat: Disable crashlytics when we want
  .env.template
  lib/src/app.dart
  lib/src/core/constants/app_configuration.dart
  pubspec.yaml
Labels: version: Minor

#91 feat(feedback): Implement feedback feature! (#28)
  .env.template
  .github/workflows/main-workflow.yaml
  .github/workflows/pr_workflow.yaml
  ios/Podfile
  lib/src/app.dart
  lib/src/core/constants/app_configuration.dart
  lib/src/core/constants/app_theme.dart
  lib/src/core/constants/regexp.dart
  lib/src/core/services/dialog_service.dart
  lib/src/core/services/info_service.dart
  lib/src/feedback/constants/feedback_form_fields.dart
  lib/src/feedback/constants/feedback_type.dart
  lib/src/feedback/feedback_view.dart
  lib/src/feedback/feedback_view_model.dart
  lib/src/feedback/service/github_service.dart
  lib/src/feedback/utils/build_issue_helper.dart
  lib/src/feedback/widgets/draggable_sheet_feedback.dart
  lib/src/feedback/widgets/feedback_form.dart
  lib/src/feedback/widgets/feedback_screenshot_form.dart
  lib/src/feedback/widgets/feedback_success_dialog.dart
  lib/src/feedback/widgets/feedback_type_selection.dart
  lib/src/locator.dart
  lib/src/router.dart
  lib/src/settings/settings_view.dart
  lib/src/settings/settings_view_model.dart
  lib/src/settings/widgets/button_item.dart
  localization/en.arb
  localization/fr.arb
  pubspec.lock
  pubspec.yaml
  test/src/feedback/feedback_view_model_test.dart
  test/src/feedback/widgets/feedback_form_test.dart
  test/src/feedback/widgets/feedback_screenshot_form_test.dart
  test/src/feedback/widgets/feedback_success_dialog_test.dart
  test/src/feedback/widgets/feedback_type_selection_test.dart
  test/src/settings/settings_view_model_test.dart
  test/src/settings/widgets/button_item_test.dart
Labels: enhancement, version: Minor, platform: iOS, platform: android, feature: settings
