Repository RoadTripMoustache/kana_to_kanji, pull requests merged in 2024-05, with the labels that each got.

#234 chore: Old database clean up
  assets/database/data.json
  lib/src/core/constants/group_queries.dart
  lib/src/core/constants/kana_queries.dart
  pubspec.yaml
Labels: version: Minor

#238 chore: Bump dependencies and enable dependabot
  .github/dependabot.yaml
  .github/workflows/main-workflow.yaml
  .github/workflows/pr_workflow.yaml
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/src/core/widgets/arc_progress_indicator.dart
  lib/src/core/widgets/rounded_linear_progress_indicator.dart
  pubspec.lock
  pubspec.yaml
Labels: version: Patch

#247 chore: Update flutterfire_cli version to fix an issue.
  .github/workflows/main-workflow.yaml
  .github/workflows/pr_workflow.yaml
  pubspec.yaml
Labels: version: Patch

#235 refactor: Kana, Kanji, Vocabulary id into UID
  lib/src/core/constants/resource_type.dart
  lib/src/core/models/example.dart
  lib/src/core/models/group.dart
  lib/src/core/models/kana.dart
  lib/src/core/models/kanji.dart
  lib/src/core/models/kanji_reading.dart
  lib/src/core/models/pronunciations.dart
  lib/src/core/models/resource_uid.dart
  lib/src/core/models/vocabulary.dart
  lib/src/core/repositories/kana_repository.dart
  lib/src/core/services/kana_service.dart
  lib/src/core/utils/isar_utils.dart
  lib/src/glossary/widgets/kana_list.dart
  lib/src/quiz/quiz_view_model.dart
  pubspec.yaml
  test/src/core/repositories/kana_repository_test.dart
  test/src/core/repositories/kanji_repository_test.dart
  test/src/core/repositories/vocabulary_repository_test.dart
  test/src/core/widgets/furigana_text_test.dart
  test/src/glossary/details/details_view_test.dart
  test/src/glossary/details/widgets/details_test.dart
  test/src/glossary/widgets/glossary_list_tile_test.dart
  test/src/glossary/widgets/kana_list_test.dart
  test/src/glossary/widgets/kana_list_tile_test.dart
  test/src/glossary/widgets/kanji_list_test.dart
  test/src/glossary/widgets/vocabulary_list_test.dart
  test/src/quiz/conclusion/quiz_conclusion_view_model_test.dart
  test/src/quiz/conclusion/widgets/question_review_tile_test.dart
  test/src/quiz/conclusion/widgets/to_review_section_test.dart
  test/src/quiz/prepare/widgets/group_card_test.dart
Labels: version: Minor

#236 chore: Migrate to Isar Community
  pubspec.lock
  pubspec.yaml
Labels: version: Minor

#237 refactor: Call /sync to know which data sync needs to be done
  lib/src/core/models/sync.dart
  lib/src/core/services/sync_service.dart
  lib/src/locator.dart
  pubspec.yaml
Labels: version: Minor

#239 feat: Update the process calling /cleanup
  lib/src/core/models/cleanup.dart
  lib/src/core/repositories/groups_repository.dart
  lib/src/core/repositories/kana_repository.dart
  lib/src/core/repositories/kanji_repository.dart
  lib/src/core/repositories/vocabulary_repository.dart
  lib/src/core/services/cleanup_service.dart
  lib/src/core/services/groups_service.dart
  lib/src/core/services/kana_service.dart
  lib/src/core/services/kanji_service.dart
  lib/src/core/services/vocabulary_service.dart
  lib/src/locator.dart
  pubspec.yaml
Labels: version: Minor

#251 fix: Paginate Kanji and Vocabulary list to reduce display cost
  lib/src/glossary/widgets/vocabulary_list.dart
  pubspec.yaml
Labels: version: Minor

#259 fix: Update breaking change configuration from library `device_info_plus`
  .github/workflows/main-workflow.yaml
  .github/workflows/pr_workflow.yaml
  android/app/build.gradle
  pubspec.yaml
Labels: version: Patch

#254 perf(glossary): Improve `KanaList` render performance
  ios/Runner.xcodeproj/project.pbxproj
  lib/src/glossary/widgets/kana_list.dart
  pubspec.yaml
Labels: enhancement, version: Patch, UI, feature: glossary

#250 test: Add dummy data
  pubspec.yaml
  test/dummies/group.dart
  test/dummies/kana.dart
  test/dummies/kanji.dart
  test/dummies/vocabulary.dart
  test/src/core/repositories/kana_repository_test.dart
  test/src/core/repositories/kanji_repository_test.dart
  test/src/core/repositories/vocabulary_repository_test.dart
  test/src/core/widgets/furigana_text_test.dart
  test/src/glossary/details/details_view_test.dart
  test/src/glossary/details/widgets/details_test.dart
  test/src/glossary/widgets/glossary_list_tile_test.dart
  test/src/glossary/widgets/kana_list_test.dart
  test/src/glossary/widgets/kana_list_tile_test.dart
  test/src/glossary/widgets/kanji_list_test.dart
  test/src/glossary/widgets/vocabulary_list_test.dart
  test/src/quiz/conclusion/quiz_conclusion_view_model_test.dart
  test/src/quiz/conclusion/widgets/question_review_tile_test.dart
  test/src/quiz/conclusion/widgets/to_review_section_test.dart
  test/src/quiz/prepare/widgets/group_card_test.dart
Labels: version: Minor

#252 fix: Only execute search, filter and sort on the current tab
  lib/src/core/constants/glossary_tab.dart
  lib/src/glossary/glossary_view.dart
  lib/src/glossary/glossary_view_model.dart
  lib/src/glossary/widgets/vocabulary_list.dart
  pubspec.lock
  pubspec.yaml
  test/src/glossary/glossary_view_model_test.dart
Labels: version: Minor

#258 fix: Align icons
  lib/src/core/widgets/chip_list.dart
  lib/src/feedback/widgets/feedback_type_selection.dart
  lib/src/glossary/widgets/filter_by.dart
  lib/src/glossary/widgets/search_bar.dart
  lib/src/glossary/widgets/sort_by.dart
  lib/src/quiz/conclusion/quiz_conclusion_view.dart
  lib/src/quiz/prepare/prepare_quiz_view.dart
  lib/src/quiz/quiz_view.dart
  lib/src/quiz/widgets/question_tile.dart
  lib/src/settings/settings_view.dart
  lib/src/settings/settings_view_model.dart
  pubspec.yaml
  test/src/feedback/widgets/feedback_type_selection_test.dart
  test/src/settings/widgets/tile_item_test.dart
Labels: version: Patch

#253 fix: Improve sorting of japanese words
  lib/src/core/models/kanji.dart
  lib/src/core/models/vocabulary.dart
  lib/src/core/utils/kana_utils.dart
  lib/src/glossary/widgets/vocabulary_list.dart
  pubspec.yaml
  test/src/core/utils/kana_utils_test.dart
Labels: version: Minor

#255 feat: inform that a new version is available
  lib/src/app.dart
  lib/src/core/widgets/app_snack_bar_upgrader.dart
  localization/en.arb
  localization/fr.arb
  pubspec.lock
  pubspec.yaml
Labels: version: Minor

#260 feat: Practice tab home skeleton
  lib/src/core/widgets/app_bottom_navigation_bar.dart
  lib/src/practice/quiz/practice_view.dart
  lib/src/practice/quiz/practice_view_model.dart
  lib/src/router.dart
  localization/en.arb
  localization/fr.arb
  pubspec.yaml
Labels: version: Minor

#261 feat: Implement User model, service and repository
  lib/src/core/constants/authentication_method.dart
  lib/src/core/constants/languages.dart
  lib/src/core/constants/learning_mode.dart
  lib/src/core/constants/resource_type.dart
  lib/src/core/dataloaders/group_dataloader.dart
  lib/src/core/dataloaders/kana_dataloader.dart
  lib/src/core/dataloaders/kanji_dataloader.dart
  lib/src/core/dataloaders/user_dataloader.dart
  lib/src/core/dataloaders/vocabulary_dataloader.dart
  lib/src/core/models/user.dart
  lib/src/core/models/user_achievement.dart
  lib/src/core/models/user_achievement_level_unlocked.dart
  lib/src/core/models/user_learning.dart
  lib/src/core/models/user_learning_progression.dart
  lib/src/core/models/user_preferences.dart
  lib/src/core/repositories/user_repository.dart
  lib/src/core/services/cleanup_service.dart
  lib/src/core/services/user_service.dart
  lib/src/locator.dart
  pubspec.yaml
Labels: version: Minor
